name: Pull Request ChatOps Template
on:
  issue_comment:
    types: [created]

jobs:
  example:
    name: Example ChatOps command
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: refs/pull/${{ github.event.issue.number }}/head
    - if: startsWith(github.event.comment.body, '/bump')
      run: |
        echo ${{github.event.comment.body}}
