name: Pull Request ChatOps Template
on:
  issue_comment:
    types: [created]

jobs:
  example:
    name: Example ChatOps command
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v1
    - if: startsWith(github.event.comment.body, '/bump')
      run: |
        body="${{github.event.comment.body}}"
        new=${body#"/bump "}
        commit=$(git rev-parse HEAD)
        git_refs_url=$(jq .repository.git_refs_url $GITHUB_EVENT_PATH | tr -d '"' | sed 's/{\/sha}//g')
        echo $git_refs_url
        curl -s -X POST $git_refs_url \
        -H "Authorization: token $GITHUB_TOKEN" \
        -d @- << EOF
        {
          "ref": "refs/tags/$new",
          "sha": "$commit"
        }
        EOF
